import 'app/global.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ lobby }: any) {
  return (
    <html lang="en">
      <body>{lobby}</body>
    </html>
  );
}
